meta:
  version: 2
  flow: FABulousTile
  substituting_steps:
    # KLayout runs density check, TODO disable
    #KLayout.DRC: null

FABULOUS_TILE_DIR: dir::. #tiles/S_term_DSP

# Basics
DESIGN_NAME: S_term_DSP
VERILOG_FILES:
  - dir::../../models_pack.v
  - dir::../../custom.v

# Clock
CLOCK_PERIOD: 20
CLOCK_PORT: UserCLK

# Area
FP_SIZING: absolute
pdk::sky130A:
    DIE_AREA: [0, 0, 199.64, 55.76]
    
    ROUTING_OBSTRUCTIONS:
    - [met2, 0, 55.76, 199.64, 56.76]
    
pdk::ihp-sg13g2:
    DIE_AREA: [0, 0, 196.32, 59.22]
